### ISSUE TITLE
My library only supports up to 5.4 not symfony6 , and my pull requests always fail when symfony6 checks automatically

### ISSUE THREAD

**Issue by CJayHe** [symfony/recipes-contrib#1423]
My library only supports up to 5.4 not symfony6 , and my pull requests always fail when symfony6 checks automatically

how do i do it ？

**link :** [ADD v2 #1422](https://github.com/symfony/recipes-contrib/pull/1422)

**Comment by lyrixx** [comment]
@nicolas-grekas I checked, and it looks like we [always](https://github.com/symfony/recipes/blob/main/.github/workflows/callable-qa.yml#L280) try to load recipes with SF 6. This looks strange

**Comment by nicolas-grekas** [comment]
GHA scripts need some love, PR welcome :)

**Comment by lyrixx** [comment]
@CJayHe would you mind to submit a PR to fix that?

**Comment by CJayHe** [comment]
@lyrixx Yes. I am glad to

**Comment by CJayHe** [comment]
@lyrixx I wrote a version and submitted it but the machine verification failed because this is not a recipe submission and needs manual review

**Comment by outcomer** [comment]
> GHA scripts need some love, PR welcome :)

Hi @nicolas-grekas 👋

I ran into exactly the same issue described here with the Git Flow script exit codes and the missing compatibility prompt while trying to pass tests for receipt PR for https://github.com/symfony/recipes-contrib/pull/1923

For me the issue was that my bundle does not support Symfony < 7, but GHS script just does not show assumed msg:
"You can ignore this error if your package does not support Symfony 6"

I’ve opened a PR that addresses this behavior:  
https://github.com/symfony/recipes/pull/1510

The change ensures that:
- the exit code from the recipe script is properly handled  
- the compatibility prompt is shown even when Composer returns a non-zero status  
- the UX matches what was originally expected in this issue

Happy to adapt the implementation 👍

probably same problem was here https://github.com/symfony/recipes-contrib/issues/1172#issuecomment-891233725
