### ISSUE TITLE
Travis CI error: "parameters" should be defined via the "container" configurator instead

### ISSUE THREAD

**Issue by vatri** [symfony/recipes-contrib#680]
Why I am getting this error?

If I replace `parameters` with `container`, then my bundle stop working.

```
In vatri/google-drive-bundle/0.2/config/packages/vatri_google_drive.yaml:

> @@ -0,0 +1,28 @@
+parameters:
"parameters" should be defined via the "container" configurator instead
```

**Comment by maxhelias** [comment]
The parameter section refers only to the root folder of the configuration and not for any bundle.

Flex can add any parameters with the container configurator like this : https://github.com/symfony/recipes-contrib/blob/02cdaf98603aafda4b6f41fa7e4ac1cba3d630e1/google/recaptcha/1.1/manifest.json#L12

Otherwise, you can set you parameters on your packages file like this : 
https://github.com/symfony/recipes-contrib/blob/02cdaf98603aafda4b6f41fa7e4ac1cba3d630e1/friendsofsymfony/rest-bundle/2.2/config/packages/fos_rest.yaml#L2

And use the DependencyInjection to automatically configure your project

**Comment by vatri** [comment]
Thank you @maxhelias . 

I will try with second solution later. 

For now I am trying to go without this config file.

**Comment by Nyholm** [comment]
Thank you @maxhelias. Im going to close this issue. 

@vatri: I hope Maxime's answer solved it for you

**Comment by vatri** [comment]
I don't have time to check yet but I think it will work. Will reopen if needed. 

Thanks again.
